version: '3.1'

services:
  # MySQL database
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/:ro
    stdin_open: true
    tty: true

  # Python3 + Flask
  python-api:
    container_name: python-api
    build: ./python
    links:
      - db
    depends_on:
      - db
    ports:
      - "8080:8080"
  
  # VueJS + ExpressJS
  express-api:
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    links:
      - db
    depends_on:
      - db
    container_name: express-api
    volumes:
        - ./express:/usr/src/app/express
        - /usr/src/app/express/node_modules
  vue-ui:
    build:
      context: ./vue
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    container_name: vue-ui
    volumes:
        - ./vue:/usr/src/app/vue
        - /usr/src/app/vue/node_modules
  
  # AngularJS + MeteorJS
  meteor-api:
    build:
      context: ./meteor
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    container_name: meteor-api
    volumes:
        - ./meteor:/usr/src/app/meteor
        - /usr/src/app/meteor/node_modules
  angular-ui:
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - "8082:4200"
    container_name: angular-ui
    volumes:
      - ./angular:/usr/src/app/angular
      - /usr/src/app/angular/node_modules

  # ReactJS + NextJS
  react-ui:
    build:
      context: ./reactjs
      dockerfile: Dockerfile
    ports:
      - "8083:3000"
    container_name: react-ui
    volumes:
      - ./reactjs:/usr/src/app/reactjs
      - /usr/src/app/reactjs/node_modules
  next-api:
    build:
      context: ./next
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    links:
      - db
    depends_on:
      - db
    container_name: next-api
    volumes:
        - ./next:/usr/src/app/next
        - /usr/src/app/next/node_modules

  # Elm + Clojure
  elm-ui:
    build:
      context: ./elm
      dockerfile: Dockerfile
    ports:
      - "8084:8000"
    container_name: elm-ui
    volumes:
      - ./elm:/usr/src/app/elm
      - /usr/src/app/elm/node_modules
  clojure-api:
    build:
      context: ./clojure_backend
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    links:
      - db
    depends_on:
      - db
    container_name: clojure-api
    volumes:
        - ./clojure_backend:/usr/src/app/clojure_backend